---
- name: Verify
  hosts: all

  tasks:
    - name: Check Claude Code is installed
      ansible.builtin.command: "{{ ansible_facts['env']['HOME'] }}/.local/bin/claude --version"
      register: claude_version
      changed_when: false

    - name: Assert Claude Code output
      ansible.builtin.assert:
        that:
          - "'Claude Code' in claude_version.stdout"
