---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Create users to configure
      ansible.builtin.user:
        name: "{{ item }}"
        create_home: true
      loop:
        - molecule
        - molecule-norepos

  roles:
    - role: git
      git_users:
        - name: molecule
          full_name: Molecule Tester
          email: molecule@example.com
          repositories:
            - bruzit/.github
        - name: molecule-norepos
          repositories: []
