---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check git is installed
      ansible.builtin.command: git --version  # noqa: command-instead-of-module
      register: git_version
      changed_when: false

    - name: Check git is configured
      ansible.builtin.command: git config --get push.autoSetupRemote  # noqa: command-instead-of-module
      register: git_config_push_auto_setup_remote
      changed_when: false

    - name: Read the per-user git configuration
      become: true
      become_user: molecule
      ansible.builtin.command: git config --global --list  # noqa: command-instead-of-module
      register: git_user_config
      changed_when: false

    - name: Stat the per-user git configuration
      ansible.builtin.stat:
        path: /home/molecule/.gitconfig
      register: git_user_gitconfig

    - name: Read the cloned repository remote
      become: true
      become_user: molecule
      ansible.builtin.command: git -C /home/molecule/Projects/.github remote get-url origin  # noqa: command-instead-of-module
      register: git_user_repository_remote
      changed_when: false

    - name: Stat the cloned repository
      ansible.builtin.stat:
        path: /home/molecule/Projects/.github
      register: git_user_repository

    - name: Stat the Projects directory of the user without repositories
      ansible.builtin.stat:
        path: /home/molecule-norepos/Projects
      register: git_user_norepos_projects

    - name: Assert git output
      ansible.builtin.assert:
        that:
          - "'git version' in git_version.stdout"
          - "'true' in git_config_push_auto_setup_remote.stdout"
          - "'user.name=Molecule Tester' in git_user_config.stdout_lines"
          - "'user.email=molecule@example.com' in git_user_config.stdout_lines"
          - "'push.autosetupremote=true' in git_user_config.stdout_lines"
          - git_user_gitconfig.stat.exists
          - git_user_gitconfig.stat.pw_name == 'molecule'
          - git_user_repository_remote.stdout == 'https://github.com/bruzit/.github.git'
          - git_user_repository.stat.pw_name == 'molecule'
          - not git_user_norepos_projects.stat.exists
