---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check yq runs
      ansible.builtin.command: yq --version
      register: yq_version
      changed_when: false

    - name: Assert yq output
      ansible.builtin.assert:
        that:
          - "'mikefarah/yq' in yq_version.stdout"
