---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Assert ca-certificates is installed
      ansible.builtin.assert:
        that:
          - "'ca-certificates' in ansible_facts.packages"
