---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Assert mc is installed
      ansible.builtin.assert:
        that:
          - "'mc' in ansible_facts['packages']"

    - name: Check mc runs
      ansible.builtin.command: mc --version
      register: mc_output
      changed_when: false

    - name: Assert mc output
      ansible.builtin.assert:
        that:
          - "'GNU Midnight Commander' in mc_output.stdout"
