---
- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Set git push.autoSetupRemote to true
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
    value: "true"
