---
- name: Install the nftables rules of git
  ansible.builtin.include_role:
    name: bruzit.ansible.nftables
    tasks_from: rules
  vars:
    nftables_rules_name: git

- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Set git push.autoSetupRemote to true
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
    value: "true"

- name: Set git push.autoSetupRemote per user
  become: true
  become_user: "{{ item.name }}"
  community.general.git_config:
    name: push.autoSetupRemote
    scope: global
    value: "true"
  loop: "{{ git_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set git user.name per user
  become: true
  become_user: "{{ item.name }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ item.full_name }}"
  loop: "{{ git_users | selectattr('full_name', 'defined') }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set git user.email per user
  become: true
  become_user: "{{ item.name }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ item.email }}"
  loop: "{{ git_users | selectattr('email', 'defined') }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure SSH commit signing per user
  ansible.builtin.include_tasks: signing.yaml
  loop: "{{ git_users | selectattr('signing_key', 'defined') }}"
  loop_control:
    loop_var: git_user
    label: "{{ git_user.name }}"

- name: Create Projects directory per user
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.file:
    path: "~{{ item.name }}/Projects"
    state: directory
    mode: "0755"
  loop: "{{ git_users | selectattr('repositories', 'defined') | selectattr('repositories') }}"
  loop_control:
    label: "{{ item.name }}"

- name: Clone repositories per user
  become: true
  become_user: "{{ item.0.name }}"
  ansible.builtin.git:  # noqa: latest[git]
    repo: "https://github.com/{{ item.1 }}.git"
    dest: "~{{ item.0.name }}/Projects/{{ item.1 | split('/') | last }}"
    update: false
  loop: "{{ git_users | subelements('repositories', skip_missing=true) }}"
  loop_control:
    label: "{{ item.0.name }} {{ item.1 }}"
