---
- name: Add Flatpak remote repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Install Obsidian
  become: true
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: present
