---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: List installed Flatpak applications
      ansible.builtin.command: flatpak list --app --columns=application
      register: widelands_flatpak_apps
      changed_when: false

    - name: Assert the application is installed
      ansible.builtin.assert:
        that:
          - "'org.widelands.Widelands' in widelands_flatpak_apps.stdout"
