---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Assert gh is installed
      ansible.builtin.assert:
        that:
          - "'gh' in ansible_facts.packages"

    - name: Check gh is installed
      ansible.builtin.command: gh --version
      register: gh_version
      changed_when: false
      failed_when: gh_version.rc != 0

    - name: Assert gh output
      ansible.builtin.assert:
        that:
          - "'gh version' in gh_version.stdout"

    - name: Check apt source file exists
      ansible.builtin.command: grep -rl cli.github.com /etc/apt/sources.list.d/
      register: apt_source
      changed_when: false
      failed_when: apt_source.rc != 0

    - name: Assert apt source file exists
      ansible.builtin.assert:
        that:
          - apt_source.stdout | length > 0
