---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Create the default user
      ansible.builtin.user:
        name: molecule
        create_home: true

  roles:
    - role: wsl
      wsl_default_user: molecule
