---
- name: Stat Bash autocompletion directory
  ansible.builtin.stat:
    path: /etc/bash_completion.d
  register: bash_completion_dir

- name: Add Terraform bash autocomplete
  become: true
  ansible.builtin.copy:
    content: 'complete -C /usr/bin/terraform terraform'
    dest: /etc/bash_completion.d/terraform
    owner: root
    group: root
    mode: '0644'
  when: bash_completion_dir.stat.exists
