---
- name: Install GnuPG required by apt_repository
  become: true
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Install HashiCorp signing key
  become: true
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: "0644"

- name: Add HashiCorp apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc]
      https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main
    filename: hashicorp

- name: Install Terraform
  become: true
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true

- name: Import Bash autocomplete setup tasks
  ansible.builtin.import_tasks: bash_autocomplete.yaml
