---
- name: Install oras
  ansible.builtin.include_role:
    name: bruzit.ansible.github_binary
  vars:
    github_binary_name: oras
    github_binary_repository: oras-project/oras
    github_binary_asset: "oras_{version}_linux_amd64.tar.gz"
    github_binary_sums: "oras_{version}_checksums.txt"
    github_binary_member: oras
    github_binary_version_command: oras version
