---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Assert terraform is installed
      ansible.builtin.assert:
        that:
          - "'terraform' in ansible_facts.packages"

    - name: Check terraform is installed
      ansible.builtin.command: terraform -version
      register: terraform_version
      changed_when: false

    - name: Assert terraform output
      ansible.builtin.assert:
        that:
          - "'Terraform' in terraform_version.stdout"

    - name: Check apt source file exists
      ansible.builtin.command: grep -rl apt.releases.hashicorp.com /etc/apt/sources.list.d/
      register: terraform_apt_source
      changed_when: false

    - name: Assert apt source file exists
      ansible.builtin.assert:
        that:
          - terraform_apt_source.stdout | length > 0
