---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check Terraform is installed
      ansible.builtin.command: terraform -version
      register: terraform_version
      changed_when: false

    - name: Assert terraform output
      ansible.builtin.assert:
        that:
          - "'Terraform' in terraform_version.stdout"
