name: Ansible Molecule Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        role:
          - git

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: >
          pip install
          "ansible-core<2.19"
          molecule
          molecule-docker
          docker

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run Molecule
        working-directory: roles/${{ matrix.role }}
        run: molecule test
