---
name: MegaLinter

on:
  pull_request:

jobs:
  megalinter:
    name: MegaLinter
    uses: bruzit/github-actions-and-workflows/.github/workflows/megalinter.yaml@feature/gitleaks-pr-scope
    permissions:
      contents: write
      pull-requests: write
